### ISSUE TITLE
Injected code does not respect DECIMAL-POINT IS COMMA

### ISSUE THREAD

**Issue by oakmount66** [openmainframeproject/cobol-check#130]
In many European countries, if not all, we use comma as decimal point, and use below option in all our COBOL programs
![image](https://user-images.githubusercontent.com/60236192/121641804-f2593a00-ca8f-11eb-8581-7c6ad64962d3.png)

In the injected code you don't respect above option
![image](https://user-images.githubusercontent.com/60236192/121642305-a1961100-ca90-11eb-9a3b-1dcaececa712.png)

Which ends up in a syntax error
![image](https://user-images.githubusercontent.com/60236192/121642374-b83c6800-ca90-11eb-87ab-5112a4267d26.png)

In the old version we made this change our self in ZUTZCWS copybook, but this is not possible, if we choose to use the compiled version downloaded from https://neopragma.com/projects/cobol-check/

Is it possible to look for the DECIMAL-POINT option a decide which code to inject, or give us an entry in the config.properties to decide the value of the decimal point?

Thanks for a nice product.
Best regards
Lars Egeberg, BANKDATA.

**Comment by dakaa16** [comment]
An option has been added in the config file for DECIMAL-POINT IS COMMA. If the configuration is set to true, the injected code will respect the rule, however it is expected that the cobol compiler has defined the rule. If the source program (the one which we are testing) sets DECIMAL-POINT IS COMMA, the option set in config will be overwritten (only for the current instance), and the injected code will still respect the rule. I will be closing this issue.
