### ISSUE TITLE
Question: project activity

### ISSUE THREAD

**Issue by FALLAI-Denis** [openmainframeproject/cobol-check#152]
Hi,

Is this project still active?
Is there a date planned for a next release?
The project no longer appears on the Open Mainframe Project site ...

**Comment by Rune-Christensen** [comment]
There is a plan for releasing 0.2.0.
At the moment my company is going through the process of implementing the current version of Cobol-Check, and doing bugfixes, when we find them.
This involves verifying that code coverage data, matches that of Cobol Unit test, running a large number of our unit tests, and building the first version of a VS Code extension.
When that is done, we are releasing that as version 0.2.0.
Currently we expect that to be within the next months, depending on the issues we find.
After that, there is no plan for the following versions. 
The project is looking for interns, to keep developing, and that is a slow process. 
If you know of any candidates, please open an issue, and we will get back to you.
Regards,
Rune
