### ISSUE TITLE
Problem with sub calls.

### ISSUE THREAD

**Issue by samdion1994** [openmainframeproject/cobol-check#161]
Hi all,

Small issus but the last push broke le comments on the "**call**" segments to sub-programms. 
Is this wanted ?  

Wait... was commenting the sub programms ever a thing ?

**Comment by samdion1994** [comment]
Also if there is no MOCK 
this line is generated lines.add("       01  UT-MOCKS-GENERATED.");

this will cause an error because there is no pic attribut to it

quick fix.

    List<String> generateWorkingStorageMockCountLines(List<Mock> mocks){

        List<String> lines = new ArrayList<>();
        if (mocks.size() > 0) {
            lines.add("       01  UT-MOCKS-GENERATED.");
            lines.addAll(generateMockCountValues(mocks));
        }
        return lines;
    }

**Comment by Rune-Christensen** [comment]
Mock calls has yet to be developed. Do you have an example of what it was that broke?
@dakaa16 Can you fix the superfluous 01 element generated, and make sure there is a test for it?

**Comment by dakaa16** [comment]
I'll make sure that the code gets generated correctly if there is no mock present.

**Comment by dakaa16** [comment]
Hi @samdion1994, the generation of code when no mock is present should be fixed now. Do let me know if this fixes your issue

**Comment by Rune-Christensen** [comment]
Hi @samdion1994 
Can you confirm that the issue is fixed?
/Rune

**Comment by samdion1994** [comment]
Hi @Rune-Christensen & @dakaa16 I will comfirm this week sorry been really busy :) !

**Comment by Rune-Christensen** [comment]
Hi @samdion1994 
Just a friendly reminder to confirm that the issue is fixed :-)
/Rune

**Comment by samdion1994** [comment]
This is good for me now Thanks :)\!!!
