### ISSUE TITLE
README.md changes requested for miss-leading "Micro Focus Mainframe Express" section

### ISSUE THREAD

**Issue by StephenGennard** [openmainframeproject/cobol-check#164]
With reference to the section in the README.md about "Micro Focus Mainframe Express".

>Micro Focus has a long history in the Cobol world, and deep experience in supporting cross-platform compatibility at the source level for mainframe Cobol development off-platform.

Micro Focus provides COBOL+ tools for both Windows, Linux and Unix but we also provide tooling for working on the mainframe itself with the *[Enterprise Developer for Z](https://www.microfocus.com/en-us/products/enterprise-developer-for-z/overview)* product, so it is inaccurate to say Micro Focus only provide off-platform COBOL development tools.

You appear to have mixed up two different products which have different testing capabilities.

The *Mainframe Express* product has support for [fragment-based](https://www.microfocus.com/documentation/MainframeExpress/mx20books/ugtpov.htm) testing which although it might seem strange today, back when this product was actively used it performed its functionality well.

> The main limitation of this product is the fact it only runs on Microsoft Windows. But if the tool meets your needs, it would be a very small cost indeed to set up a dedicated Windows box or VM to run it. Even so, many developers may not find the additional bother of having to run a Windows instance worth the payoff. Those who work for a large enterprise may be provided a Windows laptop by their employer, so this consideration would not be a factor.

The *Micro Focus Mainframe Express* product has [reached end of service](https://www.microfocus.com/en-us/marketing/mainframe-express-end-of-service)

The Enterprise Developer and Visual COBOL products replace this product and has built-in support for Unit Testing for both COBOL and JCL.   It is available for use on Windows, Linux and Unix with IDE support for Visual Studio and Eclipse.

> Like other tools in this space, the Micro Focus Unit Testing Framework does not enable isolated testing of individual Cobol paragraphs.

The smallest unit of work that can be tested is a [section or paragraph](https://www.microfocus.com/documentation/visual-cobol/vc70/VS2017/GUID-66F1776E-D432-49BD-9E79-8F75FFC4C329.html).   Similarly, programs can be [stubbed and mocked.](https://www.microfocus.com/documentation/visual-cobol/vc70/VS2017/GUID-0BEAA445-3BFC-409A-A8A3-8C8F2E67FA45.html)

The support is provided by a custom preprocessor called *mfupp*.

> It also was not designed from the perspective of a test-driven development practitioner. Using it in a test-driven way requires additional effort. It has been our observation that tools requiring additional effort tend to be set aside, as developers want to focus their mental energy on solving problems rather than on wrangling tools.

This may be true for the fragment testing support in *Mainframe Express*, as its focus is on testing existing code but I disagree with this statement for the testing support provided by *Enterprise Developer & Visual COBOL*.

**Comment by StephenGennard** [comment]
With kind regards, any chance that this can be changed?

**Comment by StephenGennard** [comment]
@dakaa16, @davenicolette, @neopragma - ping... Happy to talk about this..

**Comment by Rune-Christensen** [comment]
Hi @StephenGennard 

As neither dakaa16 or I have any experience with Micro Focus tools, and davenicolette is busy, we would like to offer two solutions.

1. We remove any mention of Micro Focus tools
2. As this is open source, you can contribute, by fixing the paragraphs with errors.

We could try to rewrite based on your input above, but we feel it would not do the products from Micro Focus justice, and would therefore prefer to not do that.

Regards,
Rune

**Comment by davenicolette** [comment]
I vote for option 1 - remove mention of Micro Focus tools.

If we eventually test Cobol Check with Micro Focus tools, we can add
meaningful content at that time.

Dave

**Comment by Rune-Christensen** [comment]
Section about Micro Focus removed.
