### ISSUE TITLE
Mocked sections and paragraphs cannot handle periods in bodies

### ISSUE THREAD

**Issue by dakaa16** [openmainframeproject/cobol-check#174]
If a section/paragraph contains a period that does not end the section/paragraph or a call-statement it cannot be mocked successfully. The generated EVALUATE-statement for a mock might get cut off in the WHEN-OTHER-statement, and never reach END-EVALUATE.

**Comment by Rune-Christensen** [comment]
Example for this issue:
![image](https://github.com/openmainframeproject/cobol-check/assets/26797797/4dbdb47d-2ff5-4b61-a885-2813c971b26a)
The first . in this section causes COBOL Check to produce invalid test code:

Example testcase: 
![image](https://github.com/openmainframeproject/cobol-check/assets/26797797/1132440d-2d93-46c1-831a-f998c7e0d73f)

Resulting COBOL code with error from IBM compiler:
![image](https://github.com/openmainframeproject/cobol-check/assets/26797797/21a3856a-ae4a-4e19-9a20-2d207e1ccc73)
The produced code contains two evaluates, one nested in the other.
What the compiler is complaining about is that, the first . (it belongs to the original code) terminates the first evaluate, and therefore the second end-evaluate does not have a matching evaluate.

I see two possible solutions to this.
1. Throw an error, when detecting extra . in mocked sections. In modern COBOL there should only be one . used to end the section. But classic COBOL allows it on almost any line.
2. Clean the section being mocked for extra . . I do not really like this solution as some . in an evaluate could be valid.
I think I would fix this by, adding an option for choosing how COBOL Check should manage this situation, so each installation can pick their solution.  But this is extra work...

**Comment by Rune-Christensen** [comment]
The morning shower brought an even better solution.
Put the original code into a new section, and perform the section in the OTHER statement.
That manages all issues with the two solutions proposed in the previous post.
