### ISSUE TITLE
Context sensitive syntax check for unit tests

### ISSUE THREAD

**Issue by dakaa16** [openmainframeproject/cobol-check#214]
Currently Cobol Check, checks the validity of the unit test (.cut) syntax, by checking, if the last token, can be followed by the current token. This may catch a lot of syntax errors, however a lot can go unnoticed, and lead to unexpected behavior. Thus we need to make the syntax check context sensitive. When we enter an EXPECT-statement, Cobol Check needs to know that it is built the right way. The same goes for MOCK and VERIFY.

**Comment by KlausMikhaelson** [comment]
Hey @dakaa16 I have some experience with java and would like to work on this issue, can I get this assigned to me ?

**Comment by Rune-Christensen** [comment]
Hi @KlausMikhaelson 
There you go, looking forward to see your work :-)
/Rune

**Comment by dakaa16** [comment]
Has been resolved
