### ISSUE TITLE
Invoke cobol-check as a COBOL function inside of a program

### ISSUE THREAD

**Issue by KTSnowy** [openmainframeproject/cobol-check#223]
We've been testing cobol-check for our COBOL track on Exercism and from what I understand you have to use an unusual writing style for it to work, where you need to use a goback statement followed by a paragraph containing the code being tested.

The issue is that teaching students to write COBOL this way while learning the language might be a little confusing, so I was wondering if it was possible to make cobol-check work as a COBOL function or without requiring the students to use an unusual code style.

**Comment by dakaa16** [comment]
Hi @KTSnowy, I do not believe you have to start with a GOBACK for Cobol Check to work. There is some rightful confusion about Cobol Check versions, as we haven't handled versioning properly on our end. There are currently multiple different versions dubbed 0.1.0, so be sure to use [this version](https://github.com/openmainframeproject/cobol-check/blob/dist/build/distributions/cobol-check-0.1.0.zip).

**Comment by dakaa16** [comment]
As far as I could gather from the mention above, this doesn't seem to be an issue, so I'm closing this
