### ISSUE TITLE
Cobol-check always has a zero return code

### ISSUE THREAD

**Issue by 0xE282B0** [openmainframeproject/cobol-check#224]
Hi,
I was using cobol-check in a script and it always has a zero return code. No matter what the `*-gnucobol_run_tests` script returns.
The version I am using is built from sources, therefore I want to ask if you can confirm that behavior.

**Comment by dakaa16** [comment]
HI @0xE282B0 I'll get on fixing that now

**Comment by dakaa16** [comment]
Hello again @0xE282B0 I misinterpreted your issue. There was a bug regarding return codes, however not regarding the return code of the script. I believe it would be confusing, letting Cobol Check return the return code of the script, as it might be seen as Cobol Check not running as expected. I do however also see the benefit of simply relying on a return code to see if all test assertions was successful. If it's something you need, we could make this a feature request
