### ISSUE TITLE
Support for MOCK and VERIFY CALL arguments without commas

### ISSUE THREAD

**Issue by dakaa16** [openmainframeproject/cobol-check#252]
Currently this can be parsed:
`           MOCK CALL 'PROG3' USING
             BY CONTENT VALUE-1,
             BY VALUE VALUE-2,
             VALUE-3`

This cannot be parsed:
`           MOCK CALL 'PROG3' USING
             BY CONTENT VALUE-1
             BY VALUE VALUE-2
             VALUE-3`

Both should be able to get parsed

**Comment by issacto** [comment]
I am interested in working on this issue
