### ISSUE TITLE
Support ON EXCEPTION in CALLs

### ISSUE THREAD

**Issue by Rune-Christensen** [openmainframeproject/cobol-check#276]
Ensure that COBOL Check supports the following COBOL:

CALL "PROGRAM" USING PROGRAM-DATA
  ON EXCEPTION 
   PERFORM ERROR-HANDLING
END-CALL

and

CALL "PROGRAM" USING PROGRAM-DATA
  ON EXCEPTION 
   PERFORM ERROR-HANDLING
.

Currently COBOL Check will only comment the first line of the CALL statement, and not all lines to END-CALL.

**Comment by prernadabi23** [comment]
@Rune-Christensen, Hello, I'm Prerna Dabi and I'm really interested in working on this project as an LFX mentee for this 
summer. I would like to work on this issue.

**Comment by Rune-Christensen** [comment]
Hi @prernadabi23 
Thank you for the interest in COBOL Check.
Unfortunately the LFX mentee position has already been filled. 
If you still are interested in solving this issue, please let me know.
Thank you :-)

**Comment by Rune-Christensen** [comment]
Hi @AkashKumar7902 
There you go, please be aware that another developer is also working on issues with the call statement.
Thank you :-)
