### ISSUE TITLE
Enable COBOL Check to issue warnings/errors when a call statement is not mocked.

### ISSUE THREAD

**Issue by Rune-Christensen** [openmainframeproject/cobol-check#288]
To enable truly isolated unit tests, we want to provide an option to trigger errors or warnings, when a call statement is not mocked.
A call statement in a mocked section or paragraph should not throw an error.

**Comment by Rune-Christensen** [comment]
Hi @AkashKumar7902 
I would like a behavior where all unmocked call statements raise an error or warning.
Whether it should be an error or warning, should be determined by a configuration variable.
The configuration variable should default to warning.

When a call statement is inside a section/paragraph, where the section/paragraph is mocked, the call statement should be considered mocked.

I hope that clears up the issue :-)

**Comment by AkashKumar7902** [comment]
@Rune-Christensen 
can you please assign me this issue ?

**Comment by AkashKumar7902** [comment]
Hey @Rune-Christensen 
Please close this issue.
