### ISSUE TITLE
getting errors when trying to run test for simple fizzbuzz function

### ISSUE THREAD

**Issue by johnathan2709** [openmainframeproject/cobol-check#290]
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/2b96d892-edc7-43e8-ab1e-fe1c433105d0)
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/d14eaa87-d21a-4d1b-839f-b7758ec1f0b0)
what does this error mean and how to solve it

**Comment by Rune-Christensen** [comment]
Hi @johnathan2709 
Thank you for your interest in COBOL Check.
It appears you are running version 0.1.0, is it possible for you to upgrade to version 0.2.7?
A lot of bugs are removed in the later version.
Also, where did you get the version you are running, we might need to do some cleanup, to ensure that the correct version is distributed.
Regards,
Rune

**Comment by johnathan2709** [comment]
@Rune-Christensen I went to [wiki](https://github.com/openmainframeproject/cobol-check/wiki/Getting-Started) and then under the download section on [the project home page](https://neopragma.com/projects/Cobol%20Check/). from the download section of the neopragma page, I downloaded the latest release.
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/b32b83bb-8ebf-4ebf-8d7f-ac1a83be4f30)

**Comment by Rune-Christensen** [comment]
Ok, thank you for the link.
That page is very much out of date, I will remove the link to it.

Ok, I do not know the current command for running COBOL Check, but I can get that for you tomorrow.

Until then, do you know that there is a Visual Studio Code extension for COBOL Check?
That might be easier for you to use?

**Comment by sam94dion** [comment]
@johnathan2709 

Try: sudo -s ./cobol-check -p NUMBERS :)

**Comment by OfficialAkashKumar** [comment]
@sam94dion 
![image](https://github.com/openmainframeproject/cobol-check/assets/91385321/295704a4-7141-49d3-a14e-811fc73ee4fd)
i am still getting an error

**Comment by johnathan2709** [comment]
@sam94dion 
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/212bfe4b-b5e0-4cdd-afd2-d2e22c1457c1)

**Comment by dakaa16** [comment]
Hi @johnathan2709 
It's a problem regarding CRLF and LF. The linux scripts has been edited in Windows, and it seems we've mistakenly added a CRLF instead of LF. Linux don't understand the CRLF and interprets it as ^M, which becomes part of your path. Go to the cobolcheck script file and the scripts\linux_gnucobol_run_tests file and make sure that they are with LF. Hope this can get you going 😄.

**Comment by OfficialAkashKumar** [comment]
@dakaa16 
![image](https://github.com/openmainframeproject/cobol-check/assets/91385321/22e1bc0b-db33-4b73-837a-a8a750eec728)
still the same issue. 
i have few questions.
why there are two cobolcheck files ?
![image](https://github.com/openmainframeproject/cobol-check/assets/91385321/f6867788-8f5c-4a99-b8c9-c1d5e086be0f),
what is the purpose of CC##99.cbl file?
and do you know how to install gnucobol on windows ?

**Comment by johnathan2709** [comment]
@dakaa16 
![image](https://github.com/openmainframeproject/cobol-check/assets/91385321/22e1bc0b-db33-4b73-837a-a8a750eec728)
still the same issue. 
i have few questions.
why there are two cobolcheck files ?
![image](https://github.com/openmainframeproject/cobol-check/assets/91385321/f6867788-8f5c-4a99-b8c9-c1d5e086be0f),
what is the purpose of CC##99.cbl file?
and do you know how to install gnucobol on windows ?

**Comment by dakaa16** [comment]
DId you also change it in the cobolcheck script file?
I was under the impression that you were working in linux, but if you are working in windows, you should not have to do anything to the linux scripts.
The cobolcheck file, will run cobolcheck on mac/linux and the cobolcheck.cmd wil run cobolcheck on Windows.
The CC##99.cbl file, is the COBOL program that is generated to run through your tests. The linux/windows_gnucobol_run_tests will then use GnuCOBOL to turn the CC##99.cbl into an executable file, and run it to get the test results. 
Get GnuCOBOL [here](https://gnucobol.sourceforge.io/) 
If you are still experiencing problems, take a look at the wiki, to make sure you haven't missed anything. If this doesn't help, I'll try to look further into your problem 😃

**Comment by johnathan2709** [comment]
@dakaa16 
I did went past the above error by running the command from cygwin terminal in windows. but I am getting yet another error.
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/6c6bc9ba-a498-4dde-86ea-6576e716ae05)

**Comment by johnathan2709** [comment]
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/3d640432-8650-49e4-9054-f6075ea38546)

It worked 🥳 
the problem was that the directory which contained cobol-check repo consisted of spaces in its name that is 'D:\github repo' and cobol-check apparently only supports directory names without spaces as apparent from this error log
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/102716d2-be04-4234-a1a0-eec12e8b9dab)

**Comment by dakaa16** [comment]
Hi @johnathan2709 
Great that you got it to work and thank you for reporting the bug. It was known, but never documented. I've created a new issue #292 to cover the bug, so I will be closing this issue now.
