### ISSUE TITLE
CobolCheck cannot handle spaces in paths

### ISSUE THREAD

**Issue by dakaa16** [openmainframeproject/cobol-check#292]
When running cobolcheck, the run will fail, if there is a space at any point in the full path, to the COBOL-file you are referencing or its unit test files. See example: #290.
This should be fixed so that spaces are allowed in the paths.

**Comment by johnathan2709** [comment]
If I change add a log statement for example in some file , how do i run the project with that change. I mean ./cobolcheck -p SUM 
will search for bin/cobol-check-0.2.7.jar which doesn't contain my changes.

**Comment by johnathan2709** [comment]
Ok! i think i got what i should 
I am running gradle build but build is failing with the following error 
![image](https://github.com/openmainframeproject/cobol-check/assets/136617248/8d3f2393-755b-4178-89c5-27cc1c7372fe)

**Comment by johnathan2709** [comment]
@dakaa16 
Hey,
do you have an idea what is causing the error ?

**Comment by dakaa16** [comment]
Hi @johnathan2709
This is unrelated to this issue. If you run into new problems, please create a new issue, or use the cobolcheck slack channel.
I am not familiar with the ArchiveName method, I'm not sure what we are using it for. It seems to be deprecated, so I will create a new issue, for getting that sorted. Until it's fixed, you can ensure that your java and gradle versions are the same as described in the wiki.

**Comment by johnathan2709** [comment]
@dakaa16 
could you please provide the slack channel link ?

**Comment by AkashKumar7902** [comment]
Can anyone please check if this issue also comes in Linux ?

**Comment by AkashKumar7902** [comment]
@dakaa16 I have made a pull request with the necessary changes.
pull request: #298

**Comment by dakaa16** [comment]
Hi @johnathan2709 here is an invitation link to [Open Mainframe Project slack channel](https://join.slack.com/t/openmainframeproject/shared_invite/zt-1yeqiif86-Z1MiXvpZAUJ8MGCxjfBe2w). Here you can find the Cobol Check channel

**Comment by AkashKumar7902** [comment]
@Rune-Christensen I think this issue has been resolved. If not, what's the current status ?

**Comment by Rune-Christensen** [comment]
@AkashKumar7902 
I think you are right, I do not know why it wasn't closed with your PR.
