### ISSUE TITLE
Getting errors when running javadoc task

### ISSUE THREAD

**Issue by AkashKumar7902** [openmainframeproject/cobol-check#297]
### Description:
I am getting the 3 errors while running `./gradlew.bat javadoc`
```cmd
D:\githubrepo\cobol-check-Developer\src\main\java\org\openmainframeproject\cobolcheck\features\testSuiteParser\TestSuiteParser.java:797: error: invalid use of @return
     * @return - the next token from the testSuiteReader.
       ^
D:\githubrepo\cobol-check-Developer\src\main\java\org\openmainframeproject\cobolcheck\services\StringHelper.java:93: error: bad use of '>'
     * Ex.: "     Hey  \n" => "     Hey"
                            ^
D:\githubrepo\cobol-check-Developer\src\main\java\org\openmainframeproject\cobolcheck\services\StringHelper.java:126: error: bad use of '>'
     * Example: swapChars("1.000.000,00", '.', ',') => "1,000,000.00"
                                                     ^
```

### Java Version:
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)

### System Information:
OS: Windows 11 10.0

**Comment by AkashKumar7902** [comment]
Hi,
I have proposed a pull request with the necessary changes . The above issue's solution is discussed below:

1. invalid use of @return
```cmd
D:\githubrepo\cobol-check-Developer\src\main\java\org\openmainframeproject\cobolcheck\features\testSuiteParser\TestSuiteParser.java:797: error: invalid use of @return
     * @return - the next token from the testSuiteReader.
       ^
```

In https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#@return, it is mentioned that we should omit @return for methods that return void.
>Omit @return for methods that return void and for constructors

2. bad use of  '>'
This has to do with super-strict doclint tool in Java 8
reference: https://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

Pull Request: #298

**Comment by Rune-Christensen** [comment]
Hi @AkashKumar7902 
Thank you for the suggestion.
At this moment, we do not want to use javadoc on this project.
I can raise it at the next Technical Steering Committee meeting, but I doubt that we want to commit to document everything after javadoc standards, at this moment.
Regards,
Rune
