### ISSUE TITLE
[BUG] If a numeric field is defined across 2 lines, it gets parsed as an alphanumeric field.

### ISSUE THREAD

**Issue by WildtBrian** [openmainframeproject/cobol-check#302]
In InterpreterControllerTest, the it_updates_numeric_fields test, can be made to fail, if the WS-COUNT field is split across two lines like this:

![image](https://github.com/openmainframeproject/cobol-check/assets/71374315/948bbe76-9a11-4199-a7a8-73d056a451a2)

**Comment by AkashKumar7902** [comment]
@Rune-Christensen 
Can you please assign me to this issue ?

**Comment by Rune-Christensen** [comment]
There you go @AkashKumar7902
