### ISSUE TITLE
Warn user when mocking same item multiple times

### ISSUE THREAD

**Issue by AlexKotsc** [openmainframeproject/cobol-check#94]
Warn or throw error when user mocks fx. same section twice. 
For inexperienced users or when working on larger test suites it would be nice to provide easy to understand feedback as to why ones test case is perhaps not behaving as intended.

**Comment by neopragma** [comment]
Question: Do you mean when the user mocks the same thing twice in the same test case? It's okay to mock the same resource in different test cases, as each test case may require different behaviors from that resource.

**Comment by AlexKotsc** [comment]
Hi @davenicolette 

In our internal user guide it states the following known issues with mocking;

MOCK
A MOCK is global to the unit test and all test cases are affected no matter where in the unit test a MOCK is placed.
Every unit test component can only contain 10 MOCK statements
You can only MOCK the same SECTION once per unit test.

In your question you imply that mocking within a testcase is scoped for only that testcase. 
I could try to produce an example (and by doing so, learning if this is still an issue)

**Comment by Rune-Christensen** [comment]
Hi
In the original COBOL Unit test code, what @AlexKotsc states is correct for all mock types.

So the questions is rather, should COBOL-Check change this beahavior so mocks are local to the testcase, or should they still be global in the test suite.
Alternatively, should it be possible to do both global and local mocks?
So mocks defined outside a testcase are global, and mocks defined inside a testcase are local?

**Comment by davenicolette** [comment]
OK, I understand better now. Short answer for me is "yes," Cobol Check
should change this behavior.

The cobol-unit-test project did not consider scope at all.

Based on Alex's feedback, I've modified a document on the Cobol Check wiki
where I'm capturing design ideas for mock support. Cobol Check does not
have any support for mocks yet. This is a good time to consider design
ideas and lessons your team has learned by using cobol-unit-test. Section
1.4 in this document is based on Alex's ideas. Please let me know if this
looks okay for now, or if you have some additional ideas about it.
https://github.com/neopragma/cobol-check/wiki/Approach-to-Mocks

I'm going to tell John Mertic that we can set up a regularly-scheduled team
call sometime in the general time frames you suggested. I'll let you know
how that goes.

I'm very happy that you and Alex are interested in contributing to the
project. You have a perspective based on experience that no one else has.

Best,
Dave
